
CREATE DATABASE IF NOT EXISTS XI;
CREATE USER IF NOT EXISTS 'XIu'@'localhost' IDENTIFIED BY '1019@xI.db#1o1';
GRANT ALL PRIVILEGES ON XI.* TO 'XIu'@'localhost';
FLUSH PRIVILEGES;

USE XI;
SET foreign_key_checks = 0;